### ISSUE TITLE
LinBus is still not resolved by BOM

### ISSUE THREAD

**Issue by PierreSchwang** [IntellectualSites/bom#229]
LinBus' groupId seems to be com.enginehub.lin-bus whereas the repository only includes the group org.enginehub (as well as com.sk89q - though that's not relevant). Therefor the most recent change does not seem to work.

**Comment by PierreSchwang** [comment]
Seems like the issue does not exist? At least linbus is properly resolved by FastAsyncWorldEdit-Core-Libs for me, so I'm gonna close this

**Comment by PierreSchwang** [comment]
https://discord.com/channels/268444645527126017/344128526435221505/1263321732777906268

**Comment by dordsor21** [comment]
Is it a not using Java 21 issue?

**Comment by PierreSchwang** [comment]
Mhm, that might be a good reason - I couldn't reproduce it so I linked the discord message

**Comment by PierreSchwang** [comment]
Was never going to work as expected - EH repo is added do API documentation
